
###API 1
GET http://localhost:3000/todos/?status=TO%20DO

###
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###
GET http://localhost:3000/todos/?search_q=play

###API 2
GET http://localhost:3000/todos/?priority=HIGH

###API 3
POST http://localhost:3000/todos/
Content-Type:application/json

{
"id":10,
"todo":"Finalise Event Theme",
"prioriy":"LOW",
"status":"TO DO"
}

###API 4
PUT http://localhost:3000/todos/2
Content-Type: application/json

{
    "status":"DONE"
}

###API 5
DELETE http://localhost:3000/todos/3